language: java
jdk:
  - oraclejdk8
  
sudo: required

#services:
#  - docker
  
cache:
  directories:
  - $HOME/.m2
  
before_install:
  - export HOST_IP_ADDR=$(hostname --ip-address)
  - echo $HOST_IP_ADDR
  - sudo apt-get install -y sshpass
  - sudo groupadd docker
  - sudo useradd -d /home/me -g docker -m -p $(echo "testpasswd" | openssl passwd -1 -stdin) testuser
  - sudo sshpass -p "testpasswd" ssh testuser@localhost
  - ifconfig
  - exit
#  - sudo curl -fsSL https://get.docker.com/ | sh
##  - sudo usermod -aG docker travis #does not work, because it takes effect after relogin to the shell, but we cannot relogin on travis ci
#  - sudo docker run --rm hello-world
#  - sudo docker version
#  - sudo docker pull selenium/standalone-firefox:2.48.2
#  - sudo docker pull mongo
#  - sudo docker pull jboss/wildfly:8.2.1.Final
#  - sudo docker run -d -p 4243:2375 -v /var/run/docker.sock:/var/run/docker.sock jarkt/docker-remote-api

script:
  - mvn clean verify #-P dockermaven -Ddocker.host=$HOST_IP_ADDR -Ddocker.port=4243
#"sudo sudo -u travis -g docker -E xy" runs xy as travis user in the docker group, so we can use "docker..." 
#instead of "sudo docker" inside mvn verify.

#sudo -E su travis -c
