language: java
jdk:
  - oraclejdk8
  
sudo: required
  
cache:
  directories:
  - $HOME/.m2
  
before_install:
  - export HOST_IP_ADDR=$(hostname --ip-address)
  - echo $HOST_IP_ADDR
  - sudo apt-get install linux-headers-3.13.0-63-generic
  - sudo apt-get install -y tree
  - sudo chmod 777 /etc/apt/sources.list
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" >> /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y virtualbox-5.0
  - sudo apt-get install -y dkms
  - sudo /sbin/rcvboxdrv setup
  - sudo /etc/init.d/vboxdrv setup
  - VBoxManage --version
#  - sudo apt-get install -y virtualbox --fix-missing
#  - curl -L http://download.virtualbox.org/virtualbox/5.0.20/virtualbox-5.0_5.0.20-106931~Ubuntu~precise_i386.deb > virtualbox.deb
  - curl -L https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb > vagrant.deb
#  - sudo dpkg -i virtualbox.deb
  - sudo dpkg -i vagrant.deb
#  - rm virtualbox.deb
  - rm vagrant.deb
  - vagrant version
  - sudo curl -fsSL https://get.docker.com/ | sh
  - sudo docker version
  - sudo mkdir /data
  - sudo chmod 777 /data
  - curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose version
#  Damit die einzelnen Buildzeiten vergleichbar sind, werden die Images schon hier geladen, ansonsten passiert dies beim ersten Durchlauf
#  - sudo docker pull selenium/standalone-firefox:2.48.2
#  - sudo docker pull mongo
#  - sudo docker pull jboss/wildfly:8.2.1.Final
#  - sudo docker pull n3llyb0y/wait
  
#  - sudo docker run -d -p 4243:2375 -v /var/run/docker.sock:/var/run/docker.sock jarkt/docker-remote-api
  - sudo mkdir -p /data/io
#  - sudo docker run -d -p 2222:22 -e SSHUSER=travis -e SSHPASSWD=root -e SHELLFORWARD=yes -v /data/io:/data/io whiledo/ssh-server-commands-on-host
#  - sudo /data/io/shellforward-server &
#  - sudo docker run -d -p 2223:22 -e SSHUSER=travis -e SSHPASSWD=root -v /home/travis:/home/travis whiledo/ssh-server-commands-on-host


script:
#  - mvn clean verify -P dockermaven -Ddocker.host=$HOST_IP_ADDR -Ddocker.port=4243
#  - mvn clean verify -P dockercompose -Dscpuser=travis -Ddocker.host=$HOST_IP_ADDR -Dssh.port=2222 -Dscp.port=2223
#  - mvn clean verify -P vagrantprovider -Dscpuser=travis -Ddocker.host=$HOST_IP_ADDR -Dssh.port=2222 -Dscp.port=2223
  - mvn clean verify -P vagrantprovisionervm -Dscpuser=travis -Ddocker.host=$HOST_IP_ADDR -Dssh.port=2222 -Dscp.port=2223

after_failure:
  - sudo tree -apug /home/travis/dockercompose
