language: java
jdk:
  - oraclejdk8
  
sudo: required

#services:
#  - docker
  
cache:
  directories:
  - $HOME/.m2
  
before_install:
  - sudo curl -fsSL https://get.docker.com/ | sh
  - sudo usermod -aG docker travis #does not work, because it takes effect after relogin to the shell, but we cannot relogin on travis ci
  - sudo docker run --rm hello-world
  - sudo docker version
  - sudo docker run -d -p 4243:2375 -v /var/run/docker.sock:/var/run/docker.sock jarkt/docker-remote-api

script:
  - sudo -E su travis -c 'mvn clean verify -P dockermaven -Ddocker.host=127.0.0.1 -Ddocker.port=4243'
#"sudo sudo -u travis -g docker -E xy" runs xy as travis user in the docker group, so we can use "docker..." 
#instead of "sudo docker" inside mvn verify.
